services:
  accounts:
    image: "totakai/accounts:1.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - totakai-network
  loans:
    image: "totakai/loan:1.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - totakai-network
  cards:
    image: "totakai/cards:1.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - totakai-network
networks:
  totakai-network:
    driver: "bridge"